server:
  port: 8769

# 读取本地配置文件
#spring:
#  cloud:
#    config:
#      server:
#        native:
##          配置文件位置
#          search-locations: classpath:/shared
#  application:
#    name: config-server
## 读取本地配置文件
#  profiles:
#    active: native

#读取远程git文件
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/flyleekungfu/SpringcloudConfig
          search-paths: respo
          username: flyleekungfu
          password:
      label: master
  application:
    name: config-server